### ISSUE TITLE
How to interpret depth data?

### ISSUE THREAD

**Issue by ArmandB** [rpng/ar_table_dataset#2]
I know you all have said that the depth data is untested, but how would you interpret the depth values?

From what I can tell, the data is saved as an image where the r,g,b are all identical

**Comment by ArmandB** [comment]
Sorry for the premature question here. For posterity:
![image](https://github.com/rpng/ar_table_dataset/assets/8795661/4f224986-873c-4b4c-a9e9-e2886463fa5f)
Encoding is in 16UC1 but each element in the data array is 8 bits, but there are 848x480x2 of them

To get the metric depth of the camera, multiple by the scale factor (0.001). So a value of 1000 => 1m. The data is in mm. This information is from here: https://support.intelrealsense.com/hc/en-us/community/posts/17464300886675-INTEL-D455-MATLAB-DEPTH-IMAGE

To extract from rosbag can use this python code:
```
import cv2
import rosbag
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
def main():
    bag = rosbag.Bag(args.bag_file, "r")
    bridge = CvBridge()
    print("Extracting depth images")
    for topic, msg, t in bag.read_messages(topics=["/d455/aligned_depth_to_color/image_raw"]):
        cv_img = bridge.imgmsg_to_cv2(msg, "16UC1")
        cv2.imwrite(os.path.join(depthdir, str(msg.header.stamp)+'.png'), cv_img) #written by publisher of message
```

**Comment by goldbattle** [comment]
Correct! This is the convention for depth images.
