### ISSUE TITLE
Cleaning/removing noise in the depth data

### ISSUE THREAD

**Issue by ArmandB** [rpng/ar_table_dataset#3]
![image](https://github.com/rpng/ar_table_dataset/assets/8795661/56fcec22-626c-485e-9db4-bfac93e2d6db)
I noticed when looking at the depth data that typically in the bottom left corner (and sometimes in other places) there are high amounts of noise in the ground truth.

I know the work makes no guarantees on the depth data, but do you all have like an internal script to filter some of the noise?

Thanks for any help in advance:D

**Comment by goldbattle** [comment]
You might be able to try OpenCV or PCL. You might also want to search the realsense repos (example issue talking about this: https://github.com/IntelRealSense/realsense-ros/issues/50). There is also this webpage with some example filtering from realsense directly: https://dev.intelrealsense.com/docs/depth-post-processing
